server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/belajar_rest
    username: admin_belajar
    password: password_belajar
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
